---
:verbose: true
:namespace: sidekiq
:concurrency: 7
development:
  :concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
staging:
  :concurrency: 7
production:
  :concurrency: 10
:queues:
  - [critical, 10]
  - [mailers, 5]
  - [searchkick, 4]
  - [default, 2]
  - [low, 1]
:enabled: true
:schedule:
  searchkick_reindex_worker:
    every: '1m'
    class: SearchkickReindexWorker
  notification_mention_mailer:
    every: '5m'
    class: NotificationMentionMailerWorker
  notification_mailer:
    # run on the :15 minute mark, every 4 hrs
    cron: '15 */4 * * * *'
    class: NotificationMailerWorker
